version: '3'
services:
  school_system:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ehla/school
    container_name: school
    volumes:
      - /var/www/site
    environment:
        NODE_ENV: development
    ports:
      - "80:80"

