version: '3'
services:
  school_system_backend:
    build:
      context: .
      dockerfile: Dockerfile_local
    container_name: school_backend
    volumes:
      - .:/var/www/html
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    tty: true
    ports:
      - "8000:80"
    env_file: .env.local
    links:
        - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=school_1"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:

