FROM shin1x1/laravel-on-php7-apache
MAINTAINER Kyo

RUN mkdir -p /var/www/html
WORKDIR /var/www/html
COPY . .
COPY .env.local .env

RUN composer install

RUN php artisan config:clear

CMD php artisan serve  --port=8081 --host=0.0.0.0

EXPOSE 8081