version: '3'
services:
  school_system_backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: school_backend
    volumes:
      - .:/var/www/html
    environment:
        NODE_ENV: development
    tty: true
    ports:
      - "8000:80"

