version: '3'
services:
  school_system_frontend:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: school_frontend
    volumes:
      - ./src:/opt/school_system/frontend/src
      - /opt/school_system/frontend/.tmp/serve
    environment:
        NODE_ENV: development
    ports:
      - "3000:3000"

