## DO NOT use docker to run development as the auto refresh plugin keep sync and pull => repeated call stacks ##

version: '3'
services:
  school_system_frontend:
    build:
      context: .
      dockerfile: Dockerfile_local
    container_name: school_frontend
    volumes:
      - ./src/app:/opt/school_system/frontend/src/app
      - /opt/school_system/frontend/.tmp/serve
    environment:
        NODE_ENV: development
    ports:
      - "3000:3000"

